const PROPS=PropertiesService.getScriptProperties();
const STATE_KEY='SUM_OSCARS_STATE',NOMINATIONS_KEY='SUM_OSCARS_NOMINATIONS',ADMIN_PASSWORD_KEY='ADMIN_PASSWORD',DISCORD_WEBHOOK_KEY='DISCORD_WEBHOOK_URL';
const CATEGORIES=['Most Valuable Member','Most Loyal Member','Most Funniest Member','Best Staff Member','Biggest Crashout','Best Duo','Best Profile','Best Friendgroup','Best Hater','Best Ragebaiter','Most Annoying','Best Looking Male','Best Looking Female'];
function defaultState_(){const categories={};CATEGORIES.forEach(n=>categories[n]={open:false,finalists:[],winner:null,winnerRevealed:false});return{categories,round2:false,round2Data:[],votes:{}}}
function getState_(){let raw=PROPS.getProperty(STATE_KEY);if(!raw){const s=defaultState_();saveState_(s);return s}try{const s=JSON.parse(raw),d=defaultState_();s.categories=s.categories||{};CATEGORIES.forEach(n=>{s.categories[n]=s.categories[n]||d.categories[n];s.categories[n].open=!!s.categories[n].open;s.categories[n].finalists=Array.isArray(s.categories[n].finalists)?s.categories[n].finalists:[];s.categories[n].winner=s.categories[n].winner||null;s.categories[n].winnerRevealed=!!s.categories[n].winnerRevealed});s.round2=!!s.round2;s.round2Data=Array.isArray(s.round2Data)?s.round2Data:[];s.votes=s.votes||{};return s}catch(e){const s=defaultState_();saveState_(s);return s}}
function saveState_(s){PROPS.setProperty(STATE_KEY,JSON.stringify(s))}
function out_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON)}
function jsonp_(v,cb){cb=String(cb||'callback').replace(/[^a-zA-Z0-9_.$]/g,'');return ContentService.createTextOutput(cb+'('+JSON.stringify(v)+')').setMimeType(ContentService.MimeType.JAVASCRIPT)}
function requireAdmin_(p){const expected=PROPS.getProperty(ADMIN_PASSWORD_KEY);if(!expected)throw new Error('ADMIN_PASSWORD is not configured.');if(String(p||'')!==expected)throw new Error('Invalid moderator password.')}
function publicState_(s){const categories={};CATEGORIES.forEach(n=>categories[n]={open:!!s.categories[n].open,finalists:s.round2?s.categories[n].finalists:[],winner:s.categories[n].winnerRevealed?s.categories[n].winner:null});return{ok:true,categories,round2:s.round2,round2Data:s.round2?s.round2Data:[]}}
function doGet(e){try{const p=e&&e.parameter||{},a=String(p.action||'state');if(a==='state')return p.callback?jsonp_(publicState_(getState_()),p.callback):out_(publicState_(getState_));if(a==='vote')return vote_(p);requireAdmin_(p.password);const s=getState_();if(a==='setCategory'){const c=String(p.category);if(CATEGORIES.indexOf(c)<0)throw new Error('Unknown category.');s.categories[c].open=String(p.open)==='true'}else if(a==='setRound2'){s.round2=String(p.open)==='true'}else if(a==='getNominations'){const r={ok:true,nominations:getNominations_()};return p.callback?jsonp_(r,p.callback):out_(r)}else if(a==='setFinalists'){const c=String(p.category),f=JSON.parse(String(p.data||'[]'));if(CATEGORIES.indexOf(c)<0)throw new Error('Unknown category.');if(!Array.isArray(f)||f.length!==4)throw new Error('Select exactly 4 finalists.');s.categories[c].finalists=f.map(x=>({name:String(x.name||''),pic:String(x.pic||''),votes:0}));s.categories[c].winner=null;s.categories[c].winnerRevealed=false;syncRound2_(s)}else if(a==='setWinner'){const c=String(p.category),name=String(p.name||'');if(CATEGORIES.indexOf(c)<0)throw new Error('Unknown category.');if(!s.categories[c].finalists.some(x=>x.name===name))throw new Error('Winner must be one of the four finalists.');s.categories[c].winner=name;s.categories[c].winnerRevealed=String(p.reveal)==='true'}else if(a==='clearNominations'){PROPS.deleteProperty(NOMINATIONS_KEY);return out_({ok:true})}else throw new Error('Unknown action.');saveState_(s);return p.callback?jsonp_(publicState_(s),p.callback):out_(publicState_(s))}catch(err){const r={ok:false,error:String(err.message||err)};return e&&e.parameter&&e.parameter.callback?jsonp_(r,e.parameter.callback):out_(r)}}
function syncRound2_(s){const all=[];CATEGORIES.forEach(c=>s.categories[c].finalists.forEach(x=>all.push({category:c,name:x.name,pic:x.pic,votes:Number(x.votes||0)})));s.round2Data=all}
function vote_(p){try{const s=getState_();if(!s.round2)throw new Error('Round 2 is not open.');const c=String(p.category),name=String(p.name||''),voter=String(p.voter||'');if(CATEGORIES.indexOf(c)<0||!name||!voter)throw new Error('Missing vote information.');if(!s.categories[c].finalists.some(x=>x.name===name))throw new Error('That finalist is not available.');const key='VOTED_'+voter+'_'+c;if(PROPS.getProperty(key))throw new Error('You already voted in this category.');s.categories[c].finalists.forEach(x=>{if(x.name===name)x.votes=Number(x.votes||0)+1});PROPS.setProperty(key,'1');syncRound2_(s);saveState_(s);return p.callback?jsonp_(publicState_(s),p.callback):out_(publicState_(s))}catch(e){const r={ok:false,error:String(e.message||e)};return p.callback?jsonp_(r,p.callback):out_(r)}}
function doPost(e){try{const p=e&&e.parameter||{};if(String(p.action)==='submit')return submit_(p);requireAdmin_(p.password);const s=getState_(),a=String(p.action||'');if(a==='setCategory'){const c=String(p.category);if(CATEGORIES.indexOf(c)<0)throw new Error('Unknown category.');s.categories[c].open=String(p.open)==='true'}else if(a==='setRound2'){s.round2=String(p.open)==='true'}else if(a==='setFinalists'){const c=String(p.category),f=JSON.parse(String(p.data||'[]'));if(CATEGORIES.indexOf(c)<0||!Array.isArray(f)||f.length!==4)throw new Error('Choose exactly 4 finalists.');s.categories[c].finalists=f}else if(a==='setWinner'){const c=String(p.category);s.categories[c].winner=String(p.name||'');s.categories[c].winnerRevealed=String(p.reveal)==='true'}else if(a==='clearNominations'){PROPS.deleteProperty(NOMINATIONS_KEY)}else throw new Error('Unknown action.');saveState_(s);return out_({ok:true})}catch(err){return out_({ok:false,error:String(err.message||err)})}}
function submit_(p){const submitter=String(p.submitter||'').trim();if(!submitter)throw new Error('Discord username is required.');const data=JSON.parse(String(p.data||'{}')),s=getState_(),missing=[],closed=[];CATEGORIES.forEach(c=>{const v=data[c],has=Array.isArray(v)?v.some(x=>String(x||'').trim()):String(v||'').trim();if(s.categories[c].open){if(c!=='Best Friendgroup'&&!has)missing.push(c)}else if(has)closed.push(c)});if(closed.length)throw new Error('These categories are closed: '+closed.join(', '));if(missing.length)throw new Error('Please nominate someone for: '+missing.join(', '));const lock=LockService.getScriptLock();lock.waitLock(10000);try{const n=getNominations_(),nom={id:Utilities.getUuid(),submitter,data,time:new Date().toISOString()};n.push(nom);PROPS.setProperty(NOMINATIONS_KEY,JSON.stringify(n));sendDiscordWebhook_(nom)}finally{lock.releaseLock()}return out_({ok:true})}
function getNominations_(){const raw=PROPS.getProperty(NOMINATIONS_KEY);if(!raw)return[];try{const x=JSON.parse(raw);return Array.isArray(x)?x:[]}catch(e){return[]}}
function sendDiscordWebhook_(n){const w=PROPS.getProperty(DISCORD_WEBHOOK_KEY);if(!w)return;const fields=[];CATEGORIES.forEach(c=>{const v=n.data[c];if(Array.isArray(v)){const x=v.map(String).filter(Boolean).join(' + ');if(x)fields.push({name:c,value:x})}else if(String(v||'').trim())fields.push({name:c,value:String(v).trim()})});try{UrlFetchApp.fetch(w,{method:'post',contentType:'application/json',payload:JSON.stringify({username:'/SUM OSCARS',embeds:[{title:'New /SUM OSCARS Nomination',color:14121538,fields:[{name:'Submitted by',value:n.submitter}].concat(fields),timestamp:n.time}]}),muteHttpExceptions:true})}catch(e){console.log(e)}}
function initialize(){if(!PROPS.getProperty(STATE_KEY))saveState_(defaultState_())}